### ISSUE TITLE
Establishing secure connection Error

### ISSUE THREAD

**Issue by arminmacx** [CacheBrowser/cachebrowser#17]
Hi

i just installing chrome extension and i can open youtube fine but after i close my chrome each time i try to open youtube. or fb.com or other site using https it gives me this error when it try to establishing connection : 

"SSL connection error

ERR_SSL_PROTOCOL_ERROR
Hide details
Unable to make a secure connection to the server. This may be a problem with the server, or it may be requiring a client authentication certificate that you don't have."

i clear my cache and try again. but still the same.

i even install python version and run it through terminal in my mac and use 127.0.0.1:8080 as proxy but still the same

**Comment by arminmacx** [comment]
hi again

i try to install cachebrowser on my mac today and after installing it when i run it i got this error on everysite i visit,for example when visiting twitter :

`[HTTPS] twitter.com:443  <PROXYING>
Traceback (most recent call last):
  File "build/bdist.macosx-10.11-intel/egg/cachebrowser/common.py", line 18, in inner
    return func(*args, **kwargs)
  File "build/bdist.macosx-10.11-intel/egg/cachebrowser/proxy.py", line 45, in on_local_data
    self._schema = schema(self, self._buffer)
  File "build/bdist.macosx-10.11-intel/egg/cachebrowser/proxy.py", line 173, in __init__
    self._start_upstream()
  File "build/bdist.macosx-10.11-intel/egg/cachebrowser/proxy.py", line 213, in _start_upstream
    return self._connect_upstream(host, port)
  File "build/bdist.macosx-10.11-intel/egg/cachebrowser/proxy.py", line 227, in _connect_upstream
    sock.connect((ip, port))
  File "/Library/Python/2.7/site-packages/gevent-1.1rc4-py2.7-macosx-10.11-intel.egg/gevent/_socket2.py", line 220, in connect
    raise error(err, strerror(err))
error: [Errno 61] Connection refused`
