### ISSUE TITLE
ImportError: No module named 'main'

### ISSUE THREAD

**Issue by lutts** [CacheBrowser/cachebrowser#9]
Traceback (most recent call last):
  File "/usr/bin/cachebrowser", line 4, in <module>
    **import**('pkg_resources').run_script('cachebrowser==0.1.0', 'cachebrowser')
  File "/usr/lib64/python3.4/site-packages/pkg_resources/**init**.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/**init**.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib64/python3.4/site-packages/cachebrowser-0.1.0-py3.4.egg/EGG-INFO/scripts/cachebrowser", line 2, in <module>
    # EASY-INSTALL-SCRIPT: 'cachebrowser==0.1.0','cachebrowser'
  File "/usr/lib64/python3.4/site-packages/cachebrowser-0.1.0-py3.4.egg/cachebrowser/**init**.py", line 1, in <module>
ImportError: No module named 'main'

**Comment by ha-D** [comment]
Thanks, this is a Python3 issue. Only Python2.7x is supported right now.
I've opened a new issue to address this problem here #10
